# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46575c0337bbb87f9d22eb7a87ac59f76c87e897e31c38a2c099b5549c815e77228e0886f05d0a4ab6d5ba3a376495401f1ad6ffb1f565425a2f1e61a7d2fe42
  secret_client_id: 6040cdaf-7071-4959-851d-e6862834f886
  secret_client_password: sjgUCUEZOY8763@fmlg2+|%

test:
  secret_key_base: a0ca1e5d47fc572b8c7898d3cbb687c62a34612d131220c6bab9d5a1a70e501921a3db3b552faeab4a89144dd2805b21bc6ee5fa55754ca3724fa574458aa55b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
